name: "Deploy S3 & DynamoDB"

on:
  workflow_dispatch:
    inputs:
      aws_region:
        required: true
        default: 'us-east-2'
      bucket_name:
        required: true
        default: 'tfstate-ironmanav-ve3'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    name: "Deploy CloudFormation Stack"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file Terraform/aws/backend_s3.yml \
            --stack-name terraform-backend-bootstrap \
            --parameter-overrides BucketName=${{ inputs.bucket_name }} \
            --no-fail-on-empty-changeset
